server:
  port: 9090

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bank-db #db_name
    username: postgres # username
    password: postgres # user password
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    open-in-view: false
  liquibase:
    change-log: classpath:liquibase/changelog-master.yml